# Generated by Django 5.1.1 on 2024-11-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='description',
            field=models.TextField(),
        ),
    ]
