# Generated by Django 5.0.3 on 2024-07-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('suffix', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('current', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
                ('status', models.CharField(default='on hold', max_length=100, null=True)),
            ],
            options={
                'db_table': 'lawyer',
            },
        ),
    ]
