# Generated by Django 5.0.3 on 2024-07-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='status',
            field=models.CharField(default='on hold', max_length=100),
        ),
    ]
