# Generated by Django 5.1.1 on 2024-11-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerapp', '0002_alter_lawyer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('images', models.FileField(upload_to='')),
                ('cost', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Services',
            },
        ),
    ]
