# Generated by Django 5.1.1 on 2024-12-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerapp', '0003_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='current',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='experience',
            field=models.TextField(),
        ),
    ]
